import * as React from "react";
import Container from "@mui/material/Container";

const Terms = () => {
  return (
    <div style={{ margin: "125px auto" }}>
      <Container className="container">
        <div>
          <h2>TERMS</h2>
          <p>
            Undead Pastel club is a collection of digital artworks running on
            the Ethereum network using ERC721 tokens known as non fungible
            tokens(NFTs).
          </p>
          <p>
            https://undeadpastelclub.io/ is only a visual interface to allow
            users to acquire the digital artworks. Users are responsible for the
            safety and management of their own Ethereum wallet and validating
            all transactions and contracts related and generated by
            https://undeadpastelclub.io/ before approval. Also be aware that,
            since our Undead Pastel Club smart contract runs on the Ethereum
            network, it is not possible to undo, reverse or restore any
            transactions. https://undeadpastelclub.io/ and its connected
            services are provided “as is” and “as available” without warranty of
            any kind. By using https://undeadpastelclub.io/ you are accepting
            sole responsibility for any and all transactions involving Undead
            Pastel Club digital artworks.
          </p>
          <p>
            Depending on the popularity, scope and sales of the Undead Pastel
            Club NFT project, We reserve the right to adjust, change or reduce
            the roadmap displayed on https://undeadpastelclub.io. Our roadmap,
            which is displayed on undeadpastelclub.io, includes a part that will
            named “Post Sell-Out” containing elements that we will execute and
            realize only if the collection sells out. If the collection does not
            sell out, the execution of these elements will be at our sole
            discretion and may be cancelled or reduced. Our roadmap includes the
            acquisition of a land in the Metaverse. However , please note that
            we have no share in the Metaverse and no control over it. Therefore,
            we cannot guarantee the user experience and users will have to abide
            by the terms and conditions of the Metaverse. At the moment, the
            land would be in Sandbox Metaverse, but this could change depending
            on several factors, including the popularity of projects offering an
            immersive experience in the Metaverse.
          </p>
          <p>
            This project is strictly an NFT art project that could eventually
            provide utilities for its holders. However, we do not guarantee any
            profitability for the buyers and it is understood that this is not
            the goal or the reason of the project. This project should not be
            considered as an investment. The main goals of this project are to
            promote art, to have fun and to have utilities for the holders.
          </p>
          <p>
            As part of this project, we offer several giveaways. Depending on
            the popularity, scope and sales of the Undead Pastel Club NFT
            project, we reserve the right to reduce or cancel or reduce these
            giveaways. If we draw prices that are physical goods, we reserve the
            right to pay the equivalent of the prize in ETH instead of giving
            the physical prize.
          </p>
          <p>
            To enter our giveaways, you can also send an email to
            influencers@undeadpastelclub.io stating the giveaway that you want
            to enter and your Discord id.
          </p>
          <h2>OWNERSHIP</h2>
          <p>
            OWNERSHIP i. The user that is buying and minting our Undead Pastel
            Club artwork is the owner of the Non Fungible Token (NFT) crated by
            validating the transaction. Each Undead Pastel Club is an NFT on the
            Ethereum blockchain. When you purchase an NFT, you own all the
            rights to the underlying Undead Pastel Club. Ownership of the NFT is
            mediated entirely and only by the Smart Contract and the Ethereum
            Network which means that, at no point, may we seize, freeze, or
            otherwise modify the ownership of any Undead Pastel Club. ii.
            Personal Use. Subject to your continued compliance with these Terms,
            undeadPastelclub.io grants you a worldwide, royalty-free license to
            use, copy, and display the purchased Undead Pastel Club, along with
            any extensions that you choose to create or use, solely for the
            following purposes: (i) for your own personal, non-commercial use;
            (ii) as part of a marketplace that permits the purchase and sale of
            your Undead Pastel Club, provided that the marketplace
            cryptographically verifies each Undead Pastel Club owner’s rights to
            display the Undead Pastel Club and ensures that only the actual
            owner can display the Undead Pastel Club; or (iii) as part of a
            third party website or application that permits the inclusion,
            involvement, or participation of your Undead Pastel Club, provided
            that the website/application cryptographically verifies each Undead
            Pastel Club owner’s rights to display the Undead Pastel Club and
            ensures that only the actual owner can display the Undead Pastel
            Club, and provided that the Undead Pastel Club is no longer visible
            once the owner of the Undead Pastel Club leaves the
            website/application. iii. Commercial Use. Subject to your continued
            compliance with these Terms, undeadPastelclub.io grants you an
            unlimited, worldwide license to use, copy, and display the purchased
            Undead Pastel Club for the purpose of creating derivative works
            based upon the Undead Pastel Club (“Commercial Use”). Examples of
            such Commercial Use would be the use of the Undead Pastel Club to
            produce and sell merchandise products (T-Shirts etc.) displaying
            copies of the Undead Pastel Club. For the sake of clarity, nothing
            in this Section will be deemed to restrict you from (i) owning or
            operating a marketplace that permits the use and sale of Undead
            Pastel Club generally, provided that the marketplace
            cryptographically verifies each Undead Pastel Club owner’s rights to
            display the Undead Pastel Club and ensures that only the actual
            owner can display the Undead Pastel Club (ii) owning or operating a
            third party website or application that permits the inclusion,
            involvement, or participation of Undead Pastel Club generally,
            provided that the third party website or application
            cryptographically verifies each Undead Pastel Club owner’s rights to
            display the Undead Pastel Club and ensures that only the actual
            owner can display the Undead Pastel Club, and provided that the
            Undead Pastel Club is no longer visible once the owner of the
            Purchased Undead Pastel Club e leaves the website/application; or
            (iii) earning revenue from any of the foregoing.
          </p>
        </div>
      </Container>
    </div>
  );
};

export default Terms;
